---
# This playbook is used to import and export OAC projects with a WLST script

#
# Export
#
# TODO

#
# Import
#

- name: Copy SBConfig JAR and XML customization files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ oracle.user }}"
    group: "{{ oracle.group }}"
    mode: 0750
  with_items:
    - { src: "{{ oac_sbconfig_jar_file }}", dest: "{{ oac.config_dir }}/sbconfig.jar" }
    - { src: "{{ oac_sbconfig_customization_file }}", dest: "{{ oac.config_dir }}/ALSBCustomizationFile.xml" }
  tags:
    - oac-import-project

- name: Import OAC project
  shell: "{{ oac.scripts_dir }}/oac_import_project.sh >> {{ oac.logs_dir }}/oac_import_project_$(date +'%F').log 2>&1"
  tags:
    - oac-import-project
