---

- name: Install Oracle Service Bus
  shell: "java -Xms1024m -Xmx1024m -jar {{ oac_jar_path }} -silent -responseFile {{ oac.install_response_file }} > {{ oac.logs_dir }}/oac_installation_$(date +'%F').log 2>&1"

- set_fact:
    oac_already_installed: true
  when: oac_home.stat.exists
