---

- include: validate.yml
  tags:
    - always

- include: prepare.yml
  become: yes
  become_user: "{{ oracle.user }}"
  tags:
    - always

- include: install.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not oac_already_installed
  tags:
    - oac-plain-install
    - oac-install-and-init

- include: patch.yml
  become: yes
  become_user: "{{ oracle.user }}"
  tags:
    - oac-plain-install

- include: rcu.yml
  become: yes
  become_user: "{{ oracle.user }}"

- include: configure.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not oac_already_configured
  tags:
    - oac-configure
    - oac-install-and-init

- include: service.yml
  become: yes
  become_user: "{{ oracle.user }}"
  tags:
    - oac-start

- name: Add custom facts for OAC
  template:
    src: oac.fact.j2
    dest: /etc/ansible/facts.d/oac.fact
  become: yes
  become_user: root
  tags:
    - always

- include: impex.yml
  when: oac_already_configured
  become: yes
  become_user: "{{ oracle.user }}"
