---

- name: Create Ansible local facts directory
  file:
    path: /etc/ansible/facts.d
    state: directory
  become: yes
  become_user: root

- name: Create essential directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ oracle.user }}"
    group: "{{ oracle.group }}"
  with_items:
    - "{{ oac.logs_dir }}"
    - "{{ oac.scripts_dir }}"
    - "{{ oac.config_dir }}"

- name: Copy RCU passwords file
  template:
    src: rcu_passwords.j2
    dest: "{{ oracle.home_dir }}/.rcu_passwords"

- name: Copy WLST scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ oracle.user }}"
    group: "{{ oracle.group }}"
    mode: 0750
  with_items:
    - { src: oac_create_basic_domain.py, dest: "{{ oac.scripts_dir }}/oac_create_basic_domain.py" }
    - { src: oac_create_basic_domain_service.sh, dest: "{{ oac.scripts_dir }}/oac_create_basic_domain_service.sh" }
    - { src: oac_control_admin_server.py, dest: "{{ oac.scripts_dir }}/oac_control_admin_server.py" }
    - { src: oac_control_admin_server.sh, dest: "{{ oac.scripts_dir }}/oac_control_admin_server.sh" }
    - { src: oac_control_managed_servers.py, dest: "{{ oac.scripts_dir }}/oac_control_managed_servers.py" }
    - { src: oac_control_managed_servers.sh, dest: "{{ oac.scripts_dir }}/oac_control_managed_servers.sh" }
    - { src: oac_start_nodemanager.sh, dest: "{{ oac.scripts_dir }}/oac_start_nodemanager.sh" }
    - { src: oac_import_project.py, dest: "{{ oac.scripts_dir }}/oac_import_project.py" }
    - { src: oac_import_project.sh, dest: "{{ oac.scripts_dir }}/oac_import_project.sh" }

- name: Prepare OAC installation response file
  template:
    src: oac.rsp.j2
    dest: "{{ oac.install_response_file }}"
