---

#
# Compatibility verifications
#

- name: Get local facts
  setup:
    filter: "ansible_local"
  register: result

- name: Check if Oracle Service Bus version is supported
  fail:
    msg: "OAC version '{{ oac_version }}' is not valide. Supported version is '12c' !"
  when: oac_version not in oac.supported_versions

- name: Check if WebLogic and OAC versions are compatibles
  fail:
    msg: "OAC version '{{ oac_version }}' is not compatible with WLS version '{{ result.ansible_facts.ansible_local.weblogic.wls.version }}' !"
  when: result.ansible_facts.ansible_local.weblogic.wls.version != oac_version

#
# Check ressources existance
#

- name: Make sure the WebLogic home directory exists
  stat:
    path: "{{ middleware_home_dir }}/wlserver"
  register: wls_home
  become: yes
  become_user: "{{ oracle.user }}"

- fail:
    msg: "The WebLogic home directory didn't exist '{{ middleware_home_dir }}/wlserver' !"
  when: not wls_home.stat.exists

- name: Check if OAC is already installed
  stat:
    path: "{{ middleware_home_dir }}/oac"
  register: oac_home
  become: yes
  become_user: "{{ oracle.user }}"

- debug:
    msg: "Oracle Service Bus is already installed in '{{ middleware_home_dir }}/oac'"
  when: oac_home.stat.exists

- set_fact:
    oac_already_installed: true
  when: oac_home.stat.exists

- name: Check the OAC installation JAR file
  stat:
    path: "{{ oac_jar_path }}"
  register: oac_jar
  when: not oac_already_installed

- fail:
    msg: "The OAC installer JAR file is not found !"
  when: not oac_already_installed and not oac_jar.stat.exists

- name: Check if OAC is already configured
  stat:
    path: "{{ oac_domain_home }}/config/config.xml"
  register: domain_home
  become: yes
  become_user: "{{ oracle.user }}"

- debug:
    msg: "Oracle Service Bus is configured ! The config file '{{ oac_domain_home }}/config/config.xml' exists already !"
  when: domain_home.stat.exists

- set_fact:
    oac_already_configured: true
  when: domain_home.stat.exists

#
# Check if OAC schemas were created
#
- set_fact:
    oac_schemas_created: true
  when: (ansible_local.oac.db is defined) and (ansible_local.oac.db.created|bool)
